nelmio_api_doc:
    documentation:
        info:
            title: SECURITY API DEMO
            description: API Rest para la gestión de una empresa de vigilancia y seguridad
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
